-- Migration 028: Seed utbl_Org_Designation from existing designation data
-- Run after 026 and 027. DepartmentId maps to utbl_Org_Department.Id (1-19).
-- Level: 1 = highest (Supervisor/Managing Director), 2 = next, etc. IsLeader: 1 for Supervisor, TL, ATL, MD, COO, GM, Dept Manager.
-- Idempotent: only inserts if no rows exist.

SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.utbl_Org_Designation)
BEGIN
    INSERT INTO dbo.utbl_Org_Designation (DepartmentId, Name, Level, IsLeader, SortOrder)
    VALUES
        (1, N'Tracing Supervisor', 1, 1, 0),
        (1, N'Senior Tracing Leader', 2, 1, 1),
        (1, N'Assistant Tracing Leader', 3, 1, 2),
        (1, N'Tracing Technician', 4, 0, 3),
        (1, N'Junior Tracing Technician', 5, 0, 4),
        (1, N'Trainee – Tracing Technician', 6, 0, 5),
        (2, N'Technical Supervisor', 1, 1, 0),
        (2, N'Senior Technical Leader', 2, 1, 1),
        (2, N'Assistant Technical Leader', 3, 1, 2),
        (2, N'Senior Repair Technician', 4, 0, 3),
        (2, N'Junior Repair Technician', 5, 0, 4),
        (2, N'Trainee – Repair Technician', 6, 0, 5),
        (3, N'Finance Controller', 1, 1, 0),
        (3, N'Senior Account Manager', 2, 1, 1),
        (3, N'Senior Account Executive', 3, 1, 2),
        (3, N'Account Executive', 4, 0, 3),
        (3, N'Junior Account Executive', 5, 0, 4),
        (3, N'Trainee – Account Executive', 6, 0, 5),
        (4, N'Software Development Manager', 1, 1, 0),
        (4, N'Technical Lead', 2, 1, 1),
        (4, N'Sr. Developer / QA / Designer', 3, 1, 2),
        (4, N'Software Developer', 4, 0, 3),
        (4, N'Junior Software Developer', 5, 0, 4),
        (4, N'Trainee – Software Developer', 6, 0, 5),
        (5, N'Managing Director', 1, 1, 0),
        (5, N'Chief Operating Officer', 2, 1, 1),
        (5, N'General Manager', 3, 1, 2),
        (5, N'Department Manager', 4, 1, 3),
        (6, N'Packing Supervisor', 1, 1, 0),
        (6, N'Packing Team Leader', 2, 1, 1),
        (6, N'Senior Packing Staff', 3, 1, 2),
        (6, N'Packing Staff', 4, 0, 3),
        (6, N'Junior Packing Staff', 5, 0, 4),
        (6, N' Packing', 6, 0, 5),
        (7, N'Purchase Manager', 1, 1, 0),
        (7, N'Assistant Purchase Manager', 2, 1, 1),
        (7, N'Sr. Purchase Executive ', 3, 1, 2),
        (7, N'Purchase Executive', 4, 0, 3),
        (7, N'Junior Purchase Executive', 5, 0, 4),
        (7, N'Trainee – Purchase', 6, 0, 5),
        (8, N'IT Administrator', 1, 1, 0),
        (8, N'Senior IT Technician', 2, 1, 1),
        (8, N'IT TL', 3, 1, 2),
        (8, N'IT Technician', 4, 0, 3),
        (8, N'Junior IT Technician', 5, 0, 4),
        (8, N'Trainee – IT Support', 6, 0, 5),
        (9, N'Photography Supervisor', 1, 1, 0),
        (9, N'Photography Lead', 2, 1, 1),
        (9, N'Senior Photographer', 3, 1, 2),
        (9, N'Photographer', 4, 0, 3),
        (9, N'Junior Photographer', 5, 0, 4),
        (9, N'Trainee – Photographer', 6, 0, 5),
        (10, N'Inventory Manager', 1, 1, 0),
        (10, N'Store Supervisor', 2, 1, 1),
        (10, N'Senior Storekeeper', 3, 1, 2),
        (10, N'Storekeeper', 4, 0, 3),
        (10, N'Junior Storekeeper', 5, 0, 4),
        (10, N'Trainee – Inventory', 6, 0, 5),
        (11, N'Back Office Manager', 1, 1, 0),
        (11, N'Senior Back Office Supervisor', 2, 1, 1),
        (11, N'Back Office Supervisor', 3, 1, 2),
        (11, N'Back Office Executive', 4, 0, 3),
        (11, N'Junior BackOffice Executive', 5, 0, 4),
        (11, N'Trainee – BackOffice Executive', 6, 0, 5),
        (12, N'Maintenance Supervisor', 1, 1, 0),
        (12, N'Senior Maintenance TL', 2, 1, 1),
        (12, N'Maintenance ATL', 3, 1, 2),
        (12, N'Maintenance Technician', 4, 0, 3),
        (12, N'Junior Maintenance Staff', 5, 0, 4),
        (12, N'Trainee – Maintenance', 6, 0, 5),
        (13, N'Dispatch Manager', 1, 1, 0),
        (13, N'Outward Supervisor', 2, 1, 1),
        (13, N'Outward ATL', 3, 1, 2),
        (13, N'Logistics Staff', 4, 0, 3),
        (13, N'Junior Outward Staff', 5, 0, 4),
        (13, N'Trainee – Outward', 6, 0, 5),
        (14, N'HR Manager', 1, 1, 0),
        (14, N'Senior HR Executive', 2, 1, 1),
        (14, N'HR Coordinator', 3, 1, 2),
        (14, N'HR Executive', 4, 0, 3),
        (14, N'Junior HR Executive', 5, 0, 4),
        (14, N'Trainee – HR', 6, 0, 5),
        (15, N'Planning Manager', 1, 1, 0),
        (15, N'Scheduling TL', 2, 1, 1),
        (15, N'Assistant Scheduler', 3, 1, 2),
        (15, N'Planning Staff', 4, 0, 3),
        (15, N'Junior Planner', 5, 0, 4),
        (15, N'Trainee – Planning', 6, 0, 5),
        (16, N'Admin Manager', 1, 1, 0),
        (16, N'Facility Supervisor', 2, 1, 1),
        (16, N'Admin Assistant', 3, 1, 2),
        (16, N'Front Office Executive', 4, 0, 3),
        (16, N'Junior Admin Staff', 5, 0, 4),
        (16, N'Trainee – Admin', 6, 0, 5),
        (17, N'Inward Manager', 1, 1, 0),
        (17, N'Inward Supervisor', 2, 1, 1),
        (17, N'Inward ATL', 3, 1, 2),
        (17, N'Inward Operator', 4, 0, 3),
        (17, N'Junior Inward Operator', 5, 0, 4),
        (17, N'Trainee – Inward', 6, 0, 5),
        (18, N'QC Supervisor', 1, 1, 0),
        (18, N'Senior QC Leader', 2, 1, 1),
        (18, N'Assistant QC Leader', 3, 1, 2),
        (18, N'QC Technician', 4, 0, 3),
        (18, N'Junior QC Tech', 5, 0, 4),
        (18, N'Trainee – QC', 6, 0, 5),
        (19, N'Head of Strategy', 1, 1, 0),
        (19, N'Senior Business Analyst', 2, 1, 1),
        (19, N'Business Analyst', 3, 1, 2),
        (19, N'Data Analyst', 4, 0, 3),
        (19, N'Junior Business Analyst', 5, 0, 4),
        (19, N'Trainee – Business Analyst', 6, 0, 5);

    PRINT 'Migration 028: Inserted 112 designations into utbl_Org_Designation.';
END
ELSE
BEGIN
    PRINT 'Migration 028: utbl_Org_Designation already has data; skipped seed.';
END
GO
